Fahim/Tony #39
JumboCode/dillar-academy pull request #47
Opened 2024-11-16 15:41 UTC by tony1759

## Describe your changes
Implemented proper gradient banner layout
Added student enrollment indicators
Styled class cards with proper spacing and hover effects
Updated Button component to use design system colors
Added "Other Levels" section with proper styling
Improved component modularity following CDD principles
## Issue ticket number and link

## Does your code meet the acceptance criteria?
- [] Yes

## Testing done and screenshots (if relevant)
Navigation between different levels
Responsive layout on mobile and desktop
Button hover states and transitions
Loading states
Error handling for missing data
<img width="735" alt="Screenshot 2024-11-16 at 10 41 32 AM" src="https://github.com/user-attachments/assets/d8ff53d1-1a94-4984-8281-3edebbf517cc">

## Other comments

2024-11-17 18:55 UTC, myix765 requested changes
The Classes page is looking really good! Just wanted to request a few changes to make the page look more like the high fidelity Figma design.

- For the gradient could you change the color at the end of the gradient to be a darker blue? You don't have to get the colors exactly right, but right now both gradient colors look almost the same.
- In the Figma it looks like the grid for the classes has 4 columns, not 2
- Right now the levels navigation on the bottom is not using the Levels component, so the blue strip you've added is missing. Please update the Other Levels section to use the Level component. Also, for the blue strip, if you notice on the Figma the way that's done is by using an inset border only on the left side. We can do the same thing here using the box-shadow CSS rule. For more information on using box-shadow, you can look at this [site](https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow) which also has a demo area where you can play around with different values (especially the fourth one with the inset rule). Then to apply box-shadow with Tailwind, you can check [this page in the docs](https://tailwindcss.com/docs/box-shadow#arbitrary-values) which shows how to use arbitrary values to create your own custom box-shadow.

Let me know if you have any questions!

2024-11-18 23:35 UTC, myix765 requested changes

2024-11-18 23:35 UTC, myix765 commented on src/pages/Classes.jsx
> +                </div>
This code block here should use the Level component to display the levels rather than a standalone HTML block.

2024-11-20 06:07 UTC, lillian-tran requested changes
Hi guys - thank you for the awesome progress! In addition to the last couple things Megan mentioned, please also make small adjustments to the navbar (ordering of the pages, hover states/coloring, etc.) to make it closer to the Figma. You can leave the dropdown for the language as a click to drop instead of hover for now.

2024-11-20 06:09 UTC, myix765 commented on src/pages/Classes.jsx
> +                </div>
Also right now on hover the color strip on the levels go away, can you fix it so that they still show?

2024-11-25 02:46 UTC, lillian-tran approved these changes

2024-11-25 18:41 UTC, myix765 approved these changes

2024-11-25 18:41 UTC, merged