Welcome Page
JumboCode/dillar-academy pull request #57
Opened 2024-11-25 01:23 UTC by claireslee

We created the new home page and added the necessary front end details! We also worked on the language button.

41 - https://github.com/JumboCode/dillar-academy/issues/41

## Does your code meet the acceptance criteria?
- [x] Yes    # put an x in the brackets to checkmark!

## Testing done and screenshots (if relevant)

## Other comments

2024-11-26 18:23 UTC, myix765 requested changes
Hi guys, thanks for working on the Welcome page! I think there was a little confusion about what the ticket is asking for (which is my fault cause I edited the ticket after releasing it) but the goal of the ticket wasn't to create the i18nextLng token in localStorage, that was just an example. What we want for the Welcome page is to display it if the user is a first time visitor to the site, and to do that we want to create a _**new**_ token in localStorage so that if the token doesn't exist, we know they're a new user and we create the token and them the Welcome page. Then the next time the user visits the page, the token will now exist so we show them the Home page.

Sorry if that was unclear in the ticket, let me know if you still have any questions!

2024-12-03 17:11 UTC, Sanderson28801 commented
I updated the branch and added the localstorage variable you asked for.  Should work now, sorry this took so long

2024-12-08 18:13 UTC, myix765 approved these changes

2024-12-08 18:30 UTC, myix765 commented
Nice job guys! I made some edits so that the Welcome page always shows up when the user first visits the site, if you're interested in how I did that feel free to look at the changes I made!

2024-12-08 18:31 UTC, merged